New Live Lab created - Leveraging Oracle Analytics Cloud with Essbase
oracle-livelabs/analytics-ai pull request #276
Opened 2024-02-19 11:45 UTC by srinivas-srinivasarangachari

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated - Yes
2. Code is correct and working - Yes
3. Links are correct - Yes
4. Make sure you enter the help email link in your manifest.json - Yes
5. Please make sure WMS URLs are updated as needed after your PR is approved - Yes

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Yes] All filenames are lower case (including folders, images, files, etc.)
- [Yes] Filenames are descriptive
- [ Yes] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ Yes] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ Yes] Image references in markdown contain an alternate text

2024-02-20 16:16 UTC, denisemyrick requested changes

2024-02-20 16:16 UTC, denisemyrick commented on essbase-oac/intro/intro.md
Follow markdown formatting requirements from QA. Getting Started should be Get Started.

2024-02-22 15:03 UTC, srinivas-srinivasarangachari commented on essbase-oac/Connect-OAC-to-Essbase-cube/connect.md
Have made the necessary changes

2024-02-22 15:03 UTC, srinivas-srinivasarangachari commented
Have made the necessary changes

2024-02-22 17:30 UTC, denisemyrick submitted a review, later dismissed

2024-02-23 16:55 UTC, ramumg approved these changes

2024-02-23 16:56 UTC, ramumg commented
Hi @srinivas-srinivasarangachari, 

Your branch is out of date. Please fix this so we can go ahead and merge this pull request.

2024-02-23 17:09 UTC, srinivas-srinivasarangachari commented
Hi

 I have fixed it, could you please check.

Thanks and Regards,
Srini
________________________________
From: ramumg ***@***.***>
Sent: 23 February 2024 10:26 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Srinivas Srinivasarangachari Ramaprasad ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] New Live Lab created - Leveraging Oracle Analytics Cloud with Essbase (PR #276)


Hi @srinivas-srinivasarangachari<https://urldefense.com/v3/__https://github.com/srinivas-srinivasarangachari__;!!ACWV5N9M2RV99hQ!OGTiyfVA2CcTi0giaKQ-uOqnncuZBN9BVN3XOVAQJDOtLYJPnuS2PlCyiRZmoCvSLlYMA4GfvFvN9JCoUkL67zU9wU1eW6OvGdgacg$>,

Your branch is out of date. Please fix this so we can go ahead and merge this pull request.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/oracle-livelabs/analytics-ai/pull/276*issuecomment-1961674049__;Iw!!ACWV5N9M2RV99hQ!OGTiyfVA2CcTi0giaKQ-uOqnncuZBN9BVN3XOVAQJDOtLYJPnuS2PlCyiRZmoCvSLlYMA4GfvFvN9JCoUkL67zU9wU1eW6M_OULEXg$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/BFN4D5P2EXL6P5DUDZBFC63YVDC4PAVCNFSM6AAAAABDPJY4XGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRRGY3TIMBUHE__;!!ACWV5N9M2RV99hQ!OGTiyfVA2CcTi0giaKQ-uOqnncuZBN9BVN3XOVAQJDOtLYJPnuS2PlCyiRZmoCvSLlYMA4GfvFvN9JCoUkL67zU9wU1eW6NOkABXCw$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-02-23 22:06 UTC, merged