#11642 - Changes to Manifest file & other small updates.
oracle-livelabs/analytics-ai pull request #338
Opened 2024-08-28 15:22 UTC by pavanmanuguri

# 11642

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

2024-08-28 16:20 UTC, carmenberdant1 requested changes
Hi @pavanmanuguri, please make sure all your file names are lowercase, and check your images to have the compartment blurred. Additionally, you need to have some URLs replaced, I will DM you about this.

2024-08-29 08:32 UTC, klazarz requested changes
please make conflicts are resolved and all filenames are lower case

2024-08-29 08:32 UTC, klazarz commented on ce-genai-ocw24/workshops/desktop/index.html
<a href="https://oracle.com/livelabs" target="_blank" id="livelabs" title="Oracle LiveLabs"></a>


the url livelabs.oracle.com

2024-08-29 08:32 UTC, klazarz commented on ce-genai-ocw24/workshops/sandbox/index.html
<a href="https://oracle.com/livelabs" target="_blank" id="livelabs" title="Oracle LiveLabs"></a>


the url livelabs.oracle.com

2024-08-29 08:32 UTC, klazarz commented on ce-genai-ocw24/workshops/tenancy/index.html
<a href="https://oracle.com/livelabs" target="_blank" id="livelabs" title="Oracle LiveLabs"></a>


the url livelabs.oracle.com

2024-08-29 12:52 UTC, pavanmanuguri commented on ce-genai-ocw24/workshops/sandbox/index.html
updated

2024-08-29 12:52 UTC, pavanmanuguri commented on ce-genai-ocw24/workshops/tenancy/index.html
updated

2024-08-29 16:30 UTC, klazarz commented
@pavanmanuguri filenames are still not all lowercase. you need to either use new names or use 'git mv' to rename.

2024-08-30 07:16 UTC, klazarz reviewed
@pavanmanuguri please make sure index.html are correct:

   <a href="https://oracle.com/livelabs" target="_blank" id="livelabs" title="Oracle LiveLabs"></a>

The URL should be livelabs.oracle.com

2024-08-30 11:18 UTC, klazarz submitted a review, later dismissed

2024-08-30 11:56 UTC, pavanmanuguri commented
Resolved all conflicts, please complete this merge.

2024-08-30 12:47 UTC, klazarz approved these changes

2024-08-30 12:47 UTC, merged