Common Analytics labs updates
oracle-livelabs/analytics-ai pull request #92
Opened 2022-12-22 22:20 UTC by NagwangGyamtso

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2022-12-23 01:00 UTC, arabellayao requested changes
Hi! Please fix the following issues of your PR:
1. Add the WMS ID of the web-semantic-modeler folder to this PR
2. For common-labs/workshops/desktop and sandbox, make sure you are using the correct "Get Started" and "Need Help" labs, as suggested on the self QA form or the sample-workshop.
Thanks!

2022-12-23 14:49 UTC, NagwangGyamtso commented
Applied changes.


[Oracle]<http://www.oracle.com/>
Nagwang Gyamtso
Product Manager, Product Strategy, Analytics
LinkedIn: Linkedin.com/in/nagwanggyamtso/<https://www.linkedin.com/in/nagwanggyamtso/>
Mobile: +1.646.637.3997
Oracle Analytics

From: Arabella Yao ***@***.***>
Date: Thursday, December 22, 2022 at 8:00 PM
To: oracle-livelabs/analytics-ai ***@***.***>
Cc: Nagwang Gyamtso ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/analytics-ai] Common Analytics labs updates (PR #92)

@arabellayao requested changes on this pull request.

Hi! Please fix the following issues of your PR:

  1.  Add the WMS ID of the web-semantic-modeler folder to this PR
  2.  For common-labs/workshops/desktop and sandbox, make sure you are using the correct "Get Started" and "Need Help" labs, as suggested on the self QA form or the sample-workshop.
Thanks!

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/analytics-ai/pull/92*pullrequestreview-1228424976__;Iw!!ACWV5N9M2RV99hQ!IfzCOWqkc724gwaFo8ZXjjHzyst1ec-z1ZfhCEGjzjCixQVgcFfC7FFQ57NyO5o49iY_KkS_jeBcxxZFwn-qBhOaOYQOdQ$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AKJEPOSU5ZSNAORLBJB5KWDWOT2TRANCNFSM6AAAAAATHFLQVE__;!!ACWV5N9M2RV99hQ!IfzCOWqkc724gwaFo8ZXjjHzyst1ec-z1ZfhCEGjzjCixQVgcFfC7FFQ57NyO5o49iY_KkS_jeBcxxZFwn-qBhMoijQ7ag$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-23 18:55 UTC, arabellayao requested changes
Hi! Please add the WMS ID of the web-semantic-modeler folder to this PR

2023-01-03 17:50 UTC, anooshapilli approved these changes

2023-01-03 18:15 UTC, arabellayao approved these changes

2023-01-03 18:15 UTC, merged